name: Build
on:
  push:
    paths:
      - Dockerfile
      # [NOTE] Add more paths here if needed
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
